# Generated by Django 5.2 on 2025-04-15 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_app', '0002_dojo_desc_alter_ninja_dojo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dojo',
            name='desc',
        ),
    ]
